version: '3.8'

services:
  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

  cache:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
      - cache
    environment:
      - DATABASE_URL=mongodb://root:example@database:27017/esx?authSource=admin
      - REDIS_URL=redis://cache:6379

    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge



